version: "3.8"

services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - frontend-prod-data:/usr/share/nginx/html
      - uploads:/usr/share/nginx/html/uploads
    depends_on:
      - backend
    networks:
      - frontend-network

  frontend:
    container_name: frontend
    build: ./transcendance-frontend/
    volumes:
      - ./transcendance-frontend:/app # remove this line if you want to use the production build
      - frontend-node-modules:/app/node_modules/ # remove this line if you want to use the production build
      - frontend-prod-data:/app/dist
    networks:
      - frontend-network
    env_file: .env

  backend:
    container_name: backend
    depends_on:
      - db
    build: ./transcendance-backend/
    volumes:
      - ./transcendance-backend:/app # remove this line if you want to use the production build
      - backend-node-modules:/app/node_modules/ # remove this line if you want to use the production build
      - uploads:/app/uploads
      
    command: yarn start:dev
    networks:
      - frontend-network
      - backend-network
    ports:
      - "5555:5555"
    env_file: .env

  db:
    container_name: db
    image: postgres:latest
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  db:
    driver: local
  frontend-prod-data:
    driver: local
  uploads:
    driver: local
  frontend-node-modules:
  backend-node-modules:
